spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_sdk
#    username: postgres
#    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: your-256-bit-secret-change-this-for-production
    expiration-minutes: 1440